[package]
name = "raudio-synth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.5.1"
rand = "0.8.3"
num-complex = "0.4.4"
itertools = "0.12.0"
image = "0.24.8"
rusttype = "0.9.3"


[lib]
name = "raudio_synth"
path = "src/lib.rs"
