[package]
name = "raudio"
version = "1.0.0"
edition = "2021"


[dependencies]
hound = "3.5.1"
rand = "0.8.3"
num-complex = "0.4.4"
rustfft = "6.2.0"
once_cell = "1.19.0"
serde = { version = "1.0.194",features = ["derive"] }
serde_json = "1.0.115"

[[bin]]
name = "raudio"
path = "src/main.rs"
